### ISSUE TITLE
Using ng-google-chart.min.js throws error in angular

### ISSUE THREAD

**Issue by senthilprabhut** [angular-google-chart/angular-google-chart#195]
If I use ng-google-chart.js, the application works fine.

If I use the minified version (ng-google-chart.min.js), then I get the following error message in the browser console - "Controller 'googleChart', required by directive 'onReady', can't be found!"

Error: [$compile:ctreq] http://errors.angularjs.org/1.3.14/$compile/ctreq?p0=googleChart&p1=onReady
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:6:417
    at D (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:56:98)
    at A (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:241)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:299)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:316)
    at A (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:147)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:299)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:316)
    at A (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:147) 

Is this issue with the minified file or am I doing something wrong here?

**Comment by Balrog30** [comment]
Interesting.  I'd like to first note that if you're using the minified file, you're working from the gh-pages branch which is used for development and not guaranteed stable (not that anything is guaranteed under the MIT Lisence).

To trace this down it would be helpful to see some of your code, especially the HTML portion where your chart is declared.

**Comment by Balrog30** [comment]
Pretty sure this is connected to #201. I believe the connection was made in gitter chat, but I wanted to make it explicit in issues system.

**Comment by Balrog30** [comment]
Should be solved by #215. Main chart directive not renamed, but event directives have been name-spaced.
