### ISSUE TITLE
Documentation Hide A Series Example page broken

### ISSUE THREAD

**Issue by CalebRouleau** [angular-google-chart/angular-google-chart#278]
When I go to this example page:

http://angular-google-chart.github.io/angular-google-chart/docs/latest/examples/hide-series/

I get the error 

angular.min.js:102 Error: [$compile:ctreq] http://errors.angularjs.org/1.3.18/$compile/ctreq?p0=googleChart&p1=agcOnSelect
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:6:417
    at M (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:56:204)
    at x (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:59:362)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:51:409)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:51:426)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:51:426)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:51:17
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:18:8
    at m.$eval (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.18/angular.min.js:126:250)(anonymous function) @ angular.min.js:102

And the chart is not displayed.

**Comment by nbering** [comment]
Hmmm. That's weird. No idea what's up with this... everything's loading OK and there's no other errors. It's saying that the controller attached to the googleChart directive is somehow unavailable to agcOnClick. This worked previously, and I don't know what's changed to break it.

**Comment by nbering** [comment]
This is fixed now. Unbelievably weird issue. Jekyll was producing excerpts and adding them as a description meta tag to the page head. The "excerpt" in this case was the tag that produces the working example, and while Jekyll is smart enough to escape the angle brackets to sanitize the HTML, it does not escape double quotes, causing it to generate invalid HTML, and breaking the example in a very unusual way.

The underlying issue isn't totally fixed (other pages could break in the future or already be broken), but I fixed it for now by over-riding the excerpt for that page.

Thanks for catching this. I didn't even realize it was broken before your reported it.
